"""empty message

Revision ID: 94cac4149973
Revises: f0c92bdac176
Create Date: 2018-10-07 12:00:19.667304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cac4149973'
down_revision = 'f0c92bdac176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['common_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('common_post', sa.Column('readCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('common_post', 'readCount')
    op.drop_table('tag')
    # ### end Alembic commands ###
